[tool.poetry]
name = "turbozero"
version = "0.1.0"
description = "vectorized alphazero/mcts in JAX"
authors = ["lowrollr <92640744+lowrollr@users.noreply.github.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
jax = "^0.4.20"
flax = "^0.7.5"
optax = "^0.1.7"
jumanji = "^0.3.1"
pgx = "^2.0.1"
wandb = "^0.16.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
